### ISSUE TITLE
拉取了仓库，看了下可以正常 使用

### ISSUE THREAD

**Issue by wangxingkang** [dragooncjw/less_error#1]
tsconfig.json配置有点问题  typings.d.ts  缺少 declare module '*.less'; 配置， 样式可以生效

**Comment by wangxingkang** [comment]
可参考 https://github.com/ts-react/react-admin-template 项目  或者 ant-design-pro项目

**Comment by dragooncjw** [comment]
非常感谢！！！不过我这个是用umi官方脚手架搭建的，tsconfig.json文件没有变更过诶

**Comment by wangxingkang** [comment]
还是以 ant-design-pro项目 为准

**Comment by dragooncjw** [comment]
好的👌，非常感谢您百忙之中抽空回答我的问题！
